### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by milooooq** [technistguru/MagicaVoxel_Importer#1]
Traceback (most recent call last):
  File "C:\Users\M***\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MagicaVoxel_Importer.py", line 85, in execute
    import_vox(path, self)
  File "C:\Users\M***\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MagicaVoxel_Importer.py", line 526, in import_vox
    bsdf.inputs["Emission Strength"].default_value = materials[id][3] * 20
KeyError: 'bpy_prop_collection[key]: key "Emission Strength" not found'

location: <unknown location>:-1

**Comment by coreysj** [comment]
I am seeing the same error. I thought it might be due to presence of a material with emit enabled, but I still get this error when importing a vox with only the default diffuse material.
